site_name: kb.tristan.ee

nav:
  - Home: index.md
  - Distibuted: distibuted_systems.md
  - AspNet: aspnetmvc.md
  - JS: javascript.md
  - TransActSQL: TSQL.md

theme: 
  name: 'material'

markdown_extensions:
  - codehilite
  