name: CI

on: 
  push:
    branches:
      - master
jobs:       
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy demo
        uses: appleboy/scp-action@master
        env:
          Host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.KEY }}
        with:
          source: ./docs
          target: ${{ secrets.LOCATION }}
