name: CI

on: 
  push:
    branches:
      - master
jobs:       
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Buiding the site
        - uses: actions/checkout@master
        - uses: actions/setup-python@v1
        - uses: dschep/install-pipenv-action@v1
        - run: pipenv run mkdocs build --clean

      - name: Copy demo
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./docs
          remote: ${{ secrets.LOCATION }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.KEY }}
