name: CI

on: 
  push:
    branches:
      - master
jobs:       
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.A }}
        with:
          source: ./docs 
          target: ${{ secrets.LOCATION }}
